/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SnorkelingRouteImport } from './routes/snorkeling'
import { Route as OralHistoryRouteImport } from './routes/oral-history'
import { Route as MapRouteImport } from './routes/map'
import { Route as FieldNotesRouteImport } from './routes/field-notes'
import { Route as ConservationRouteImport } from './routes/conservation'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as IndexRouteImport } from './routes/index'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SnorkelingRoute = SnorkelingRouteImport.update({
  id: '/snorkeling',
  path: '/snorkeling',
  getParentRoute: () => rootRouteImport,
} as any)
const OralHistoryRoute = OralHistoryRouteImport.update({
  id: '/oral-history',
  path: '/oral-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesRoute = FieldNotesRouteImport.update({
  id: '/field-notes',
  path: '/field-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConservationRoute = ConservationRouteImport.update({
  id: '/conservation',
  path: '/conservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/conservation': typeof ConservationRoute
  '/field-notes': typeof FieldNotesRoute
  '/map': typeof MapRoute
  '/oral-history': typeof OralHistoryRoute
  '/snorkeling': typeof SnorkelingRoute
  '/submit': typeof SubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/conservation': typeof ConservationRoute
  '/field-notes': typeof FieldNotesRoute
  '/map': typeof MapRoute
  '/oral-history': typeof OralHistoryRoute
  '/snorkeling': typeof SnorkelingRoute
  '/submit': typeof SubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/conservation': typeof ConservationRoute
  '/field-notes': typeof FieldNotesRoute
  '/map': typeof MapRoute
  '/oral-history': typeof OralHistoryRoute
  '/snorkeling': typeof SnorkelingRoute
  '/submit': typeof SubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conditions'
    | '/conservation'
    | '/field-notes'
    | '/map'
    | '/oral-history'
    | '/snorkeling'
    | '/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conditions'
    | '/conservation'
    | '/field-notes'
    | '/map'
    | '/oral-history'
    | '/snorkeling'
    | '/submit'
  id:
    | '__root__'
    | '/'
    | '/conditions'
    | '/conservation'
    | '/field-notes'
    | '/map'
    | '/oral-history'
    | '/snorkeling'
    | '/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionsRoute: typeof ConditionsRoute
  ConservationRoute: typeof ConservationRoute
  FieldNotesRoute: typeof FieldNotesRoute
  MapRoute: typeof MapRoute
  OralHistoryRoute: typeof OralHistoryRoute
  SnorkelingRoute: typeof SnorkelingRoute
  SubmitRoute: typeof SubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snorkeling': {
      id: '/snorkeling'
      path: '/snorkeling'
      fullPath: '/snorkeling'
      preLoaderRoute: typeof SnorkelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oral-history': {
      id: '/oral-history'
      path: '/oral-history'
      fullPath: '/oral-history'
      preLoaderRoute: typeof OralHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes': {
      id: '/field-notes'
      path: '/field-notes'
      fullPath: '/field-notes'
      preLoaderRoute: typeof FieldNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conservation': {
      id: '/conservation'
      path: '/conservation'
      fullPath: '/conservation'
      preLoaderRoute: typeof ConservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionsRoute: ConditionsRoute,
  ConservationRoute: ConservationRoute,
  FieldNotesRoute: FieldNotesRoute,
  MapRoute: MapRoute,
  OralHistoryRoute: OralHistoryRoute,
  SnorkelingRoute: SnorkelingRoute,
  SubmitRoute: SubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
